name: stream_subscriber
description: >-
  Observable objects for asynchronously listening for changes to values and
  collections, plus a mixin to easily manage streams on any class.
version: 1.0.0
homepage: https://github.com/james-alex/stream_subscriber

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
